name: scanpy-analysis
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # --- Core Python Environment ---
  - python=3.10
  - pip

  # --- Python Analysis Packages ---
  - scanpy>=1.9.3
  - celltypist>=1.7.0
  - python-igraph>=0.11
  - leidenalg>=0.10
  - anndata>=0.10
  - scikit-learn>=1.4
  - pandas>=2.0
  - matplotlib-base>=3.7
  - seaborn>=0.13
  - h5py>=3.10
  
  # --- R Environment & Simulation Packages ---
  - r-base>=4.2
  - r-argparse
  - r-matrix
  - bioconductor-splatter
  - bioconductor-polyester
  - bioconductor-biostrings
  - bioconductor-summarizedexperiment
